import { RALPH_LABEL_ESCALATED, RALPH_LABEL_IN_PROGRESS, RALPH_LABEL_QUEUED, RALPH_LABEL_STUCK } from "../github-labels";

export { RALPH_LABEL_ESCALATED, RALPH_LABEL_IN_PROGRESS, RALPH_LABEL_QUEUED, RALPH_LABEL_STUCK };

export const RALPH_RESOLVED_TEXT = "RALPH RESOLVED:";
export const RALPH_RESOLVED_REGEX = /\bRALPH\s+RESOLVED:/i;
export const RALPH_ESCALATION_MARKER_PREFIX = "<!-- ralph-escalation:id=";
export const RALPH_ESCALATION_MARKER_REGEX = /<!--\s*ralph-escalation:id=([a-f0-9]+)\s*-->/i;
